all: Transition.cpp test.cpp BA.cpp wTransition.cpp wBA.cpp rwUtils.cpp DSComparator.cpp rabitUtils.cpp DSGame.cpp

	g++ -o3 -std=c++11 Transition.cpp test.cpp BA.cpp wTransition.cpp wBA.cpp rwUtils.cpp DSComparator.cpp rabitUtils.cpp DSGame.cpp -w -o quip
