all: Transition.cpp test.cpp BA.cpp wTransition.cpp wBA.cpp rwUtils.cpp DSComparator.cpp rabitUtils.cpp

	g++ -std=c++11 Transition.cpp test.cpp BA.cpp wTransition.cpp wBA.cpp rwUtils.cpp DSComparator.cpp rabitUtils.cpp -w
